[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_marketplace = "AidJGYgmra8mZXQnPoK1xgHyzc74zYPSfh8YSnfphjQg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ivmidable/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
